version: '3'
services:
  teaser-site:
    build: ./01_teaser_site
    image: firebsae
    container_name: teaser
    ports:
      - '9005:9005'
      - '5000:5000'
    working_dir: /usr/src
    volumes:
      - ./01_teaser_site/:/usr/src/
    tty: true
